# BattleNexus-CONFIG
#
# DATABASE:
#

  Basic:
    prefix: 'ยง5[BattleNexus] '
    language: 'de_DE'
  MySQL:
    host: ''
    port: ''
    database: ''
    user: ''
    password: ''
#
#
# MESSAGES:
#
#
#
# OTHER SETTINGS:
#